name: Build and deploy ASP.Net Core app to Azure Web App - Lab05-pate1147

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Verify publish output
        run: dir "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98F134A49E4A445398AB2E83D11B4CF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A88010CE15904034A052BB5AE4932699 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D0040D745014C72965FC61787096AB2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Lab05-pate1147'
          slot-name: 'Production'
          package: .
          # app-settings-json: |  # Uncomment and configure if needed
          #   [
          #     {
          #       "name": "ConnectionStrings:DefaultConnection",
          #       "value": "${{ secrets.DATABASE_CONNECTION_STRING }}",
          #       "slotSetting": false
          #     }
          #   ]
